version: "3.8"
name: 'finance-tracker-app-backend'
services:
  finance-tracker-backend:
    image: manjosh1990/mybudget-backend
    container_name: finance-tracker-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://finance-tracker-db:5432/finance_tracker_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - BREVO_USERNAME=94dca4001@smtp-brevo.com
      - BREVO_PASSWORD=9DkPbsWS1nMNg5wh
      - BREVO_FROM_EMAIL=manjosh.1990@yahoo.com
    ports:
      - "18080:18080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      finance-tracker-db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 1GB