name: Backend Service

on:
  push:
    paths:
      - '**'
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mybudget-backend
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest checkout action

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Updated to latest setup-java action
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Keep Maven cache enabled

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and push Docker image
        run:
          ./mvnw spring-boot:build-image -DskipTests
          docker push $DOCKER_IMAGE_NAME