name: Backend Service

on:
  push:
    paths:
      - backend/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest checkout action

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Updated to latest setup-java action
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Keep Maven cache enabled

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify